// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBptzkoTVO_i8QY1v0gH2tMkMJDbIQpC_U',
    appId: '1:710838437575:web:037dcaa7359afe752f20e2',
    messagingSenderId: '710838437575',
    projectId: 'gesture-app-b9f25',
    authDomain: 'gesture-app-b9f25.firebaseapp.com',
    storageBucket: 'gesture-app-b9f25.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH2PQadnSrx4Qc9bHAVNqSZ88WJz4s84Y',
    appId: '1:710838437575:android:fe9591ac3e81fba92f20e2',
    messagingSenderId: '710838437575',
    projectId: 'gesture-app-b9f25',
    storageBucket: 'gesture-app-b9f25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyklVveBwglG_mXo2tVNDfrjvv39oqGF4',
    appId: '1:710838437575:ios:227131dea8e410492f20e2',
    messagingSenderId: '710838437575',
    projectId: 'gesture-app-b9f25',
    storageBucket: 'gesture-app-b9f25.firebasestorage.app',
    iosBundleId: 'com.example.singupPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyklVveBwglG_mXo2tVNDfrjvv39oqGF4',
    appId: '1:710838437575:ios:227131dea8e410492f20e2',
    messagingSenderId: '710838437575',
    projectId: 'gesture-app-b9f25',
    storageBucket: 'gesture-app-b9f25.firebasestorage.app',
    iosBundleId: 'com.example.singupPage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBptzkoTVO_i8QY1v0gH2tMkMJDbIQpC_U',
    appId: '1:710838437575:web:6e5def8200f69bfa2f20e2',
    messagingSenderId: '710838437575',
    projectId: 'gesture-app-b9f25',
    authDomain: 'gesture-app-b9f25.firebaseapp.com',
    storageBucket: 'gesture-app-b9f25.firebasestorage.app',
  );

}